### ISSUE TITLE
i was wondering can i get the source code to the dll's i wanna learn how they work

### ISSUE THREAD

**Issue by espero-dev** [Wylx-32k/HorionInjectorPlus#1]
im new to minecraft hacking and i wanna look at the dll's source code to learn how they work after that i wanna make a simple lil hack with some usefull utils on it i will use the imgui from https://github.com/ocornut/

**Comment by ShuitOnDiscord** [comment]
He doesnt have the source code for the dlls, he didn't make them. He just gathered them all and made an application to inject them. The 1.17.11 source code is open though, it's at https://github.com/horionclient/Horion

**Comment by espero-dev** [comment]
yea i know the people that gave him the dll's

**Comment by ShuitOnDiscord** [comment]
> yea i know the people that gave him the dll's
> 
> 

They also didn't make the dlls

**Comment by Wylx-32k** [comment]
I dont have access to the source code of these DLLs. They have a open source github but it has been archived
https://github.com/horionclient/Horion

**Comment by espero-dev** [comment]
> I dont have access to the source code of these DLLs. They have a open source github but it has been archived https://github.com/horionclient/Horion

but then where did you get the 1.20 one

**Comment by espero-dev** [comment]
and last thing do you know the code to overwrite the minecraft logo to the horion logo i need that cad so i can use it in a client im making

**Comment by ShuitOnDiscord** [comment]
> > I dont have access to the source code of these DLLs. They have a open source github but it has been archived https://github.com/horionclient/Horion
> 
> 
> 
> but then where did you get the 1.20 one

1.20 is out. All you have to do is download it from https://horion.download/dll

**Comment by espero-dev** [comment]
i thought the horion website was just done no dll updates

**Comment by ShuitOnDiscord** [comment]
> i thought the horion website was just done no dll updates
> 
> 

Oh, if I understand correctly, you think horion is dead. It was for a while, but it was recontinued

**Comment by espero-dev** [comment]
yea
